version: 0.0.0
language: python
matrix:
  include:

    - python: 3.6
      sudo: false

    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda config --add channels conda-forge
  - python -m pip install --upgrade pip
  - export PYTHONPATH=$PYTHONPATH:$(pwd)\
  - python --version
  - whereis python

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install --yes numpy scipy xarray pandas obspy bottleneck pytest
  - conda install --yes pip
  - pip install obsplus --
  - pip install python-coveralls
  - python --version
  - whereis python

# command to run tests
script:
  - pytest tests
  - py.test tests